pipeline {
    agent any

    environment {
        SERVER_IP = credentials('prod-server-ip')
    }

    stages {
        stage('Setup') {
            steps {
                sh '''
                    cd 02-single-server-deployment
                    python3 -m pip install -r requirements.txt
                '''
            }
        }
        stage('Testings') {
            steps {
                sh '''
                    cd 02-single-server-deployment
                   python3 -m pytest
                '''
            }
        }
        stage('Packaging codes') {
            steps {
               sh '''
                    cd 02-single-server-deployment
                    zip -r myapp.zip ./* -x '*.git*'
                    ls -lart
                '''
            }
        }
        stage('Deploy to prod server') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-key', keyFileVariable: 'MY_SSH_KEY', usernameVariable: 'username')]) {
                sh '''
                cd 02-single-server-deployment
                scp -i $MY_SSH_KEY -o StrictHostKeyChecking=no myapp.zip ${username}@${SERVER_IP}:/home/ec2-user/
                ssh -i $MY_SSH_KEY -o StrictHostKeyChecking=no ${username}@${SERVER_IP} << 'EOF'
                    sudo unzip -o /home/ec2-user/myapp.zip -d /home/ec2-user/app/
                    source /home/ec2-user/app/venv/bin/activate
                    cd /home/ec2-user/app/
                    python3 -m pip install -r requirements.txt
                    sudo systemctl restart flaskapp.service
EOF
            '''
        }
    }
}
    }
}
